# Generated by Django 3.2 on 2021-04-29 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('title', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='preset')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(default='defo', upload_to='documents/')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wien.preset')),
            ],
        ),
    ]
